train_smiles_path: "data/chembl/train_ae_sim_unnorm.npy"
valid_smiles_path: "data/chembl/validation_ae_sim_unnorm.npy"
test_smiles_path: "data/chembl/test_ae_sim_unnorm.npy"
vocabulary: "cache/chembl/vocabulary.pkl"
use_ranking_loss: True
num_layers: 6
num_heads: 8
model_dimension: 256
feedforward_dimension: 2048
dropout: 0.1
max_sequence_length: 128
model_type: "rnn"
